---

# defaults file for haproxy docker container installation

keepalived_config_path: "/etc/haproxy/"

keepalived_dir_mode: "0644"

keepalived_dir_owner: root

keepalived_container_name: ddni-keepalived


HOST_IP: |-
    {% for host in groups['etcd'] -%}
        {%- if hostvars[inventory_hostname]['ansible_facts']['hostname'] == host -%}
          {{ hostvars[host]['ansible_default_ipv4']['address'] }}
        {%- endif -%}
    {%- endfor -%}

KEEPALIVED_INTERFACE: |-
    {{ hostvars[inventory_hostname]['ansible_default_ipv4']['interface'] }}

KEEPALIVED_VIRTUAL_IPS: |-
   {{ hostvars[inventory_hostname]['groups']['vip'][0] }}

KEEPALIVED_NOTIFY: "/container/service/keepalived/assets/notify.sh"

docker_registry: |-
     {{ hostvars[inventory_hostname]['registry_host'] }}

HIGH_PRIORITY: 200

LOW_PRIORITY: 100

 